language: node_js
node_js:
  - 4.3.1
script:
  - npm test
cache:
  directories:
    - node_modules
notifications:
  slack:
    secure: OA/mytwcXPBysFhafH1wAAAR48N2FgexFPW1NyEm6vmVRRIathfvGt373UrO4yFK2sAlu4QPGgH5wiuSP0iNhvY6Yr4Eox9ZnoGlYQNmQiRBZ1QbN36/Lza9VB7yyGnLgm7p/OZOz+w5srgcIKgSahYEPRHQ9URt11fL3l6jWcio4EJh2Z5NEG7+8xQhF6WSeWYzxe2OVlAxsrNAI26UZ8+PKCD+1mMjAbjXLvHQTL4WfELjeReqL5E2VQRS0sXsdzqYBWC4JYChEEF94E3DZlpTWPsQSIhJLnpreBITTiinK8esQwLpVDSgijgvVRqXyJuZVmEqufc9BJBiKuHn7+ARgo0n4+58BFfLqxioNpVyOAWoULldOURvFnhAw5sQ5L1jYEzUZqmEXnefVQu1v1zSMey0bMoHWDsS4UtL6HOvEymkkN3Uvw76yQ6A1sOpWI6TBon7ngdxZy1ZLGDlym3QCftqCuLHCRGny6ujmb3uMyHBdtGbHmNTNP6yszWvNnNCDnKEqN/69cFQLKOjL2v648jcz5R2VRv1Wg+JaQOxI2l9LOehyzpgRZvlGFaeypahbsUZsG+QZGm/P/6tpihNXK39CoyEWAIeoxXK4GTJCe7zwV+vX0G3Hit5G9jBY33rMk+otqmUAeUcmCthlhgIvnOWWiUa74sppVsYKNw=
